version: 0.2

phases:
  install:
    runtime-versions:
      java:coretto11
    build:
      commands:
        - ./gradlew bootJar
    post_build:
      commands:
        -echo Build completed
  artifacts:
    files:
      - build/target/*.jar
      - scripts/*.sh
      - appspec.yml

        discard-paths:yes