version: 0.2

phases:
  install:
    runtime-versions:
      java: coretto11
    build:
      commands:
        - ./gradlew buildJar
    post_build:
      commands:
        -echo Build completed
  artifacts:
    files:
      - build/target/*.jar